### PR TITLE
Created links for Data structures

### LINKED ISSUE #5: Adding links to the animation in README.md
### Example
1. [N QUEEN](http://jhabarsinghbhati.me/DSALGO-VISUALIZER/templates/backtracking/n_queen.html)

### Code
```
[N QUEEN](http://jhabarsinghbhati.me/DSALGO-VISUALIZER/templates/backtracking/n_queen.html)
```
in README.md, we can add a hyperlink to a text using the above syntax

### PR DESCRIPTION
**Pull request by aditya28sarin**

### CODE REVIEW

**Comment by aditya28sarin** [comment]
Hey, I have added till Heap but now it is too long, you can merge this and open the issue for someone else starting after Heap, is it fine?

**Comment by jhabarsingh** [comment]
@aditya28sarin, Thanks for the contribution. 🙂

**Comment by aditya28sarin** [comment]
This is a great project you are working on! Kudos!

**Comment by jhabarsingh** [comment]
@all-contributors please add @aditya28sarin for documentation

**Pull request merged**
